import { Component } from '@angular/core';

function log(target, name, descriptor) {
  console.log(target, name, descriptor)
  // stroe the origional function in a variable
  const original = descriptor.value
  // do some manipulations with descriptor.value
  
  descriptor.value = function(...args) {
    console.log("arguments", args, "Were passed in this function")
    const result = original.apply(this, args)
    console.log("The result of the function is" , result)
    return result
  }

  // return the descriptor
  return descriptor
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor() {
    console.log("This statement was generated by the constructor", this.aSimpleMethod(5,2))
  }

  @log
  aSimpleMethod(a, b) {
    return a*a
  }
}
